name: Push to External Repo

on:
  push:
    branches:
      - 'irn-releases'    # or restrict to a specific branch
    paths-ignore: 
      #- '.github/**'
      - 'k8s/**' 
      - '.gitattributes'
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove .github directory
        run: |
          rm -rf .github

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit removal of .github (temporary commit)
        run: |
          git add -A
          git commit -m "Prepare repo for sync (exclude .github)" || echo "No changes"

      - name: Add external repo and push
        run: |
          git remote add external https://oauth2:${{ secrets.EXT_REPO_PAT }}@code.irn.justica.gov.pt/plataforma-de-registos/backoffice-componentes-transversais/art-igrp-process-studio-frontend-monorepo.git
         
          git push external HEAD:feature/zing-commits --force \
            -o merge_request.create \
            -o merge_request.target=dev \
            -o merge_request.assign="carlos.marques" \
            -o merge_request.reviewer="379" \
            -o merge_request.title="Feature/zing-commits"